import { Plugin, ResolvedConfig } from "vite";
import fs from "fs";
import path from "path";
import { glob } from "glob";

export interface LivewireMeshPluginOptions {
  /**
   * Directory containing LivewireMesh React components.
   * @default 'resources/js/livewire'
   */
  componentsDir?: string;

  /**
   * File extensions to look for.
   * @default ['.tsx', '.jsx']
   */
  extensions?: string[];

  /**
   * Output path for the auto-generated server bundle config (relative to project root).
   * @default 'prerender.config.ts'
   */
  serverConfigOutput?: string;
}

/**
 * Vite plugin for LivewireMesh that:
 * - Auto-discovers React components in the specified directory
 * - Generates client-side registration code
 * - Generates server bundle configuration for prerendering
 */
export function livewireMeshPlugin(options: LivewireMeshPluginOptions = {}): Plugin {
  const {
    componentsDir = "resources/js/livewire",
    extensions = [".tsx", ".jsx"],
    serverConfigOutput = "prerender.config.ts",
  } = options;

  let config: ResolvedConfig;
  let componentFiles: string[] = [];

  // Virtual module ID for auto-generated component registrations
  const virtualModuleId = "virtual:livewiremesh-components";
  const resolvedVirtualModuleId = "\0" + virtualModuleId;

  return {
    name: "livewiremesh",

    configResolved(resolvedConfig) {
      config = resolvedConfig;
    },

    async buildStart() {
      // Discover components
      const patterns = extensions.map((ext) => path.join(config.root, componentsDir, `**/*${ext}`));
      
      componentFiles = [];
      for (const pattern of patterns) {
        const files = await glob(pattern, { nodir: true });
        componentFiles.push(...files);
      }

      if (componentFiles.length > 0) {
        console.log(`\n📦 LivewireMesh: Found ${componentFiles.length} component(s)`);
        componentFiles.forEach((file) => {
          const relativePath = path.relative(config.root, file);
          const componentName = getComponentName(relativePath, componentsDir);
          console.log(`   • ${componentName} → ${relativePath}`);
        });
        console.log("");

        // Generate prerender config in project root (for both dev and build)
        const serverConfig = generateServerConfig(componentFiles, config.root, componentsDir);
        const configPath = path.join(config.root, serverConfigOutput);
        fs.writeFileSync(configPath, serverConfig);
        console.log(`📦 LivewireMesh: Generated ${serverConfigOutput} for prerendering\n`);
      }
    },

    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }
    },

    load(id) {
      if (id === resolvedVirtualModuleId) {
        // Generate the registration code for all discovered components
        return generateClientRegistrationCode(componentFiles, config.root, componentsDir);
      }
    },

    // Add component files to the Vite build
    config(userConfig) {
      return {
        optimizeDeps: {
          include: ["react", "react-dom"],
        },
      };
    },
  };
}

/**
 * Get the component name from a file path.
 * resources/js/livewire/react-counter.tsx → react-counter
 */
function getComponentName(filePath: string, componentsDir: string): string {
  const relativePath = filePath.replace(/\\/g, "/");
  const dirPath = componentsDir.replace(/\\/g, "/");
  
  // Remove the components directory prefix
  let name = relativePath;
  if (name.startsWith(dirPath + "/")) {
    name = name.slice(dirPath.length + 1);
  }
  
  // Remove extension
  name = name.replace(/\.(tsx|jsx|ts|js)$/, "");
  
  return name;
}

/**
 * Get the full component path for registration.
 * react-counter → resources/js/livewire/react-counter.tsx
 */
function getFullComponentPath(filePath: string, root: string): string {
  return path.relative(root, filePath).replace(/\\/g, "/");
}

/**
 * Generate the client-side registration code.
 */
function generateClientRegistrationCode(
  files: string[],
  root: string,
  componentsDir: string
): string {
  if (files.length === 0) {
    return "// No LivewireMesh components found\nexport {};";
  }

  const imports: string[] = [];
  const registrations: string[] = [];

  files.forEach((file, index) => {
    const fullPath = getFullComponentPath(file, root);
    const componentName = getComponentName(fullPath, componentsDir);
    const varName = `Component${index}`;

    imports.push(`import ${varName} from "/${fullPath}";`);
    registrations.push(`  registerMeshComponent("react", "${componentName}", ${varName});`);
  });

  return `
// Auto-generated by LivewireMesh Vite plugin
import registerMeshComponent from "@livewiremesh/registerMeshComponent";

${imports.join("\n")}

// Register all components
${registrations.join("\n")}

export {};
`.trim();
}

/**
 * Generate the server config for prerendering.
 */
function generateServerConfig(
  files: string[],
  root: string,
  componentsDir: string
): string {
  if (files.length === 0) {
    return "// No LivewireMesh components found\nexport const components = {};";
  }

  const imports: string[] = [];
  const componentEntries: string[] = [];

  files.forEach((file, index) => {
    const fullPath = getFullComponentPath(file, root);
    const componentName = getComponentName(fullPath, componentsDir);
    const varName = `Component${index}`;

    imports.push(`import ${varName} from "./${fullPath}";`);
    componentEntries.push(`  "${componentName}": ${varName},`);
  });

  return `
// Auto-generated by LivewireMesh Vite plugin
// This file is used by the prerender server

${imports.join("\n")}

export const components = {
${componentEntries.join("\n")}
};

export default components;
`.trim();
}

export default livewireMeshPlugin;
