// Auto-generated by LivewireMesh Vite plugin
// This file is used by the prerender server

import Component0 from "./resources/js/livewire/react-counter.tsx";

export const components = {
  "react-counter": Component0,
};

export default components;